### ISSUE TITLE
Recipe for handling environment variables on different levels

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-runner#31]
``` yaml
name: content

clusters:
  application:
    services:
    -
      breed:
        name: sava:1.0.0
        deployable: 'magneticio/sava:1.0.0'
        ports:
          port: 8080/http
        environment_variables:
          ENV: null
          SYMFONY_ENV: null
      environment_variables:
        ENV: accept

environment_variables:
  application.SYMFONY_ENV: prod

```

Related to https://github.com/magneticio/vamp/issues/740
