### ISSUE TITLE
time based workflows don't seem to work

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-runner#73]
using this definition:
```yaml
name: helloworkflow
kind: workflow
breed:
  reference: helloworkflow
schedule:
  time:
    period: P1Y2M3DT4H5M6S
environment_variables: {}
scale:
  cpu: 0.1
  memory: 128.00MB
  instances: 1
network: HOST
arguments: []
```
